POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNhYmZmNmJmOTNmNzAzOWM5OGY1ZDYiLCJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEZtQmtUUlNDeFA4TFl2OEVaazdESmVBU3dZdUNRRTd2em9LaU5nZUZIT1VhTjBORU03WkZlIiwicHJvZmlsZVBpYyI6IiIsInVwdm90ZWRQb3N0cyI6W10sImRvd252b3RlZFBvc3RzIjpbXSwiam9pbmVkU3VicmVkZGl0cyI6W10sImthcm1hIjowLCJkYXRlIjoiMjAyMi0wMy0yM1QwNjozNToyMC44NzhaIiwiX192IjowLCJpYXQiOjE2NDgwNDM4NTB9.-ZDu_oOOOpVLGqpEIIQclhKYw1Q53pSegT73BrasEmw"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "bob@1234"
}

###

put http://localhost:5000/subreddit/join/623b47d724a6ded7bd6e500b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsInByb2ZpbGVQaWMiOiIiLCJqb2luZWRTdWJyZWRkaXRzIjpbXSwia2FybWEiOjAsImRhdGUiOiIyMDIyLTAzLTIzVDE2OjE0OjIzLjYxN1oiLCJfaWQiOiI2MjNiNDc3ZDI0YTZkZWQ3YmQ2ZTUwMDQiLCJpYXQiOjE2NDgwNTIxMTIsImV4cCI6MTY0ODA1MjcxMn0.SHqZeF9NiHXJny4VhoMeL-GE4b6u50sGKKwh5iLWsbg

{
    "title": "subreddit_1",
    "titleDescription": "title description 1"
}
