POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNkYjIxOTVlZTgwYWQxNTUyZTlhZDIiLCJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDZITHBZWDRDSUJXNkhVODVTL01lOU9wUHdkc0xtZzBwS1JTcng3YTRYUjlpVllnN2NsUm1TIiwicHJvZmlsZVBpYyI6IiIsInVwdm90ZWRQb3N0cyI6W10sImRvd252b3RlZFBvc3RzIjpbXSwiam9pbmVkU3VicmVkZGl0cyI6W10sImthcm1hIjowLCJkYXRlIjoiMjAyMi0wMy0yNVQxMjoxMTozOS45MzFaIiwiX192IjowLCJpYXQiOjE2NDgyNjUxMjV9.ynAB6R574xXKBQ1TZ60KirzQI1Kaud86vFapfLp0a_c"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "bob@1234"
}

###

get http://localhost:5000/profile/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsInByb2ZpbGVQaWMiOiIiLCJqb2luZWRTdWJyZWRkaXRzIjpbXSwia2FybWEiOjAsImRhdGUiOiIyMDIyLTAzLTI1VDEyOjExOjM5LjkzMVoiLCJfaWQiOiI2MjNkYjIxOTVlZTgwYWQxNTUyZTlhZDIiLCJpYXQiOjE2NDgyNzA1MTksImV4cCI6MTY0ODI3MTExOX0.T45ApzF4Yw9kG-50gVIixybx4zqRHD0i155YV1PBW_4

{
    "title": "post 2",
    "subredditId": "623e9d2927fe8f92e668a91b"
}
