POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNkYjIxOTVlZTgwYWQxNTUyZTlhZDIiLCJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDZITHBZWDRDSUJXNkhVODVTL01lOU9wUHdkc0xtZzBwS1JTcng3YTRYUjlpVllnN2NsUm1TIiwicHJvZmlsZVBpYyI6IiIsInVwdm90ZWRQb3N0cyI6W10sImRvd252b3RlZFBvc3RzIjpbXSwiam9pbmVkU3VicmVkZGl0cyI6W10sImthcm1hIjowLCJkYXRlIjoiMjAyMi0wMy0yNVQxMjoxMTozOS45MzFaIiwiX192IjowLCJpYXQiOjE2NDgyMTA0NjR9.OnHM6z6PQ_oI2QPo0Y8y2lYFTB3hJj3Dz-XCxnkspwU"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "bob@1234"
}

###

post http://localhost:5000/subreddit/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsInByb2ZpbGVQaWMiOiIiLCJqb2luZWRTdWJyZWRkaXRzIjpbXSwia2FybWEiOjAsImRhdGUiOiIyMDIyLTAzLTI1VDEyOjExOjM5LjkzMVoiLCJfaWQiOiI2MjNkYjIxOTVlZTgwYWQxNTUyZTlhZDIiLCJpYXQiOjE2NDgyMTA0NjQsImV4cCI6MTY0ODIxMTA2NH0.pgCuUXEouvnd3VOtQyzGTpeW8UnxRPbOFoooG05hs2k

{
    "title": "memes",
    "titleDescription": "r/memes the original since 2008",
    "subredditPic":"https://styles.redditmedia.com/t5_2qjpg/styles/communityIcon_4fv0susv2j981.png?width=256&s=b9463b92dd5785ca5b0abfa73c83600af2527826",
    "subredditId": "623c4995bbc85751de34c46f"
}
